export const GET_CONTACTS_REQUEST = 'GET_CONTACTS_REQUEST'; 
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACT_REQUEST = 'GET_CONTACT_REQUEST'; 
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS'; 
